pan: Lab1.md Lab1_no_code.md
	pandoc --pdf-engine=xelatex -V mainfont="Liberation Serif" Lab1.md -o Lab1.pdf
	pandoc --pdf-engine=xelatex -V mainfont="Liberation Serif" Lab1_no_code.md -o Lab1_no_code.pdf

# very dirty
# merge: title.pdf Lab1.pdf Lab1_no_code.pdf
#	convert title.pdf Lab1.pdf lab1_Соколов_Б20_505.pdf
#	convert title.pdf Lab1_no_code.pdf lab1_1_Соколов_Б20_505.pdf
